--1.)	USING SUBSTRING COMMAND TO SORT NAMES BY LAST THREE LETTERS: SO, FOR THIS WE USE “SUBSTR (VARIABLE, VARIABLE_SIZE)”. 
--SO, WE SORT EMPLOYEES BY LAST THREE LETTERS:

SELECT NAME FROM 
POPULATION 
ORDER BY SUBSTR (NAME, -3);

--WE USE -3 AS WE NEED TO SORT DATA BY LAST THREE LETTERS: IN RECENT SQL,WE CAN USE “RIGHT(NAME,3)”.
